BMRBrewing/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('breweryInterface/', include('breweryInterface.urls')),
    path('admin/', admin.site.urls),
]

breweryInterface/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index),
    #APIS
    # path('create_recipe/', views.create_recipe),
    path('api/taps/', views.api_tap_list),
    path('api/taps/<int:pk>/', views.api_tap_detail),
    path('api/recipes/', views.api_recipe_list),
    path('api/recipes/<int:pk>/', views.api_recipe_detail),
    path('api/logs/', views.api_log_list),
    path('api/logs/<int:pk>/', views.api_log_detail),
    # path('taps/', views.tap_list),
    path('recipe', views.recipe_form, name='recipe_insert'),
    path('recipes/', views.recipe_list, name='recipe_list'),
    path('recipes/delete/<int:id>/', views.recipe_delete, name='recipe_delete'),
    path('recipe/<int:id>/', views.recipe_form, name='recipe_update'),
    # path('add_hops/<int:id>/', views.hop_form, name='add_hops'),
    path('log', views.log_form, name='log_insert'),
    path('logs/', views.log_list, name='log_list'),
    path('logs/delete/<int:id>/', views.log_delete, name='log_delete'),
    path('log/<int:id>/', views.log_form, name='log_update'),

    path('taps/', views.tap_list, name='tap_list'),
    path('tap/<int:id>/', views.tap_form, name='tap_update'),
    path('tapsdisplay', views.taps_display, name='taps_display'),
    
    path('schedule/', views.schedule, name='schedule'),
    # path('taps/<int:pk>/', views.tap_detail),
    # path('recipes/', views.recipe_list),
   
    # path('logs/', views.log_list),
    # path('logs/<int:pk>/', views.log_detail)
]

breweryInterface/models.py
from django.db import models
import datetime
from decimal import Decimal
import math
import numpy as np
from scipy.optimize import nnls

# Create your models here.


class Water(models.Model):
    name = models.CharField(max_length=30, default="")
    targetCalciumConcentration = models.DecimalField(max_digits=5, decimal_places=2, default='0')
    targetMagnesiumConcentration = models.DecimalField(max_digits=5, decimal_places=2, default='0')    
    targetSulfateConcentration = models.DecimalField(max_digits=5, decimal_places=2, default='0')
    targetChlorideConcentration = models.DecimalField(max_digits=5, decimal_places=2, default='0') 
  
    # projectedCalciumConcentration = 0;
    # projectedMagnesiumConcentration = 0;
    # projectedSulfateConcentration = 0;
    # projectedChlorideConcentration = 0;
    
    # suggestedGypsum = models.DecimalField(max_digits=5, decimal_places=2, default='0')
    # suggestedMGSO4 = models.DecimalField(max_digits=5, decimal_places=2, default='0')
    # suggestedCaCl2 = models.DecimalField(max_digits=5, decimal_places=2, default='0')

    def __str__(self):
        return str(self.name)

    def calculate(self):
        ratioMatrix = np.array([[61.472, 0, 71.94],[26.06,0,0],[147.47, 102.9,0],[0,0,127.48]])
        targetMatrix = np.array([self.targetCalciumConcentration,self.targetMagnesiumConcentration,self.targetSulfateConcentration,self.targetChlorideConcentration])
        suggestedValues, rnorm = nnls(ratioMatrix,targetMatrix)
        projectedValues = ratioMatrix.dot(suggestedValues)

        return (suggestedValues, projectedValues)
        
    @property
    def gypsumWght(self):
        suggestedValues, projectedValues = self.calculate()
        return round(float(suggestedValues[0]),2)
        
    @property
    def MGSO4Wght(self):
        suggestedValues, projectedValues = self.calculate()
        return round(float(suggestedValues[1]),2)
    
    @property
    def CaCl2Wght(self):
        suggestedValues, projectedValues = self.calculate()
        return round(float(suggestedValues[2]),2)  

    @property
    def calcConc(self):
        suggestedValues, projectedValues = self.calculate()
        return round(projectedValues[0],2)
        
    @property
    def magConc(self):
        suggestedValues, projectedValues = self.calculate()
        return round(projectedValues[1],2)
    
    @property
    def sulfConc(self):
        suggestedValues, projectedValues = self.calculate()
        return round(projectedValues[2],2)  

    @property
    def chlorConc(self):
        suggestedValues, projectedValues = self.calculate()
        return round(projectedValues[3],2) 

class Recipe(models.Model):
    # recipe_id = models.IntegerField(null=True, blank=True)
    name = models.CharField(max_length=30, default="")
    style = models.CharField(max_length=30, default="")
    description = models.CharField(max_length=200, default="")
    efficiency = models.DecimalField(max_digits=5, decimal_places=3, default=70)    
    pre_boil_volume = models.DecimalField(max_digits=5, decimal_places=2, default=6.5)
    # post_boil_volume = models.DecimalField(max_digits=5, decimal_places=2, default=5.5)
    # pre_boil_gravity = models.IntegerField(null=True, blank=True)
    boil_duration = models.IntegerField(null=True, blank=True)
    # abv = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    # ibu = models.IntegerField(null=True, blank=True, default=0)
    # srm = models.IntegerField(null=True, blank=True, default=0)    
    # fg = models.DecimalField(max_digits=5, decimal_places=3, default=0)    
    # post_boil_gravity = models.DecimalField(max_digits=5, decimal_places=3, default=1.000)  
    attenuation = models.IntegerField(null=True, blank=True)
    water = models.ForeignKey(Water, on_delete=models.SET_NULL, null=True)
    mash_temp = models.IntegerField(null=True, blank=True, default=150)
    strike_volume = models.DecimalField(max_digits=5, decimal_places=2, default=7)
    fermentation_temp = models.IntegerField(null=True, blank=True, default = 165)

    def __str__(self):
        return(self.name)

    @property
    def total_malt_weight(self):
        maltset = self.malt_set.all()
        totalWeight = 0
        for malt in maltset:
            totalWeight = totalWeight + malt.weight
        return round(totalWeight,2)

    @property
    def strike_water_temp(self):
        GRAIN_TEMPERATURE = 70
        water_grain_ratio = (self.strike_volume*4)/self.total_malt_weight   
        a = 0.2/float(water_grain_ratio)
        return round((a)*(self.mash_temp-GRAIN_TEMPERATURE)+self.mash_temp,0)

    @property
    def post_boil_volume(self):
        BOILOFFRATE = 1 #gallon per hour
        a = float(self.boil_duration)/float(60)
        b = a*BOILOFFRATE
        c = float(self.pre_boil_volume)-float(b)
        return c
        # return self.pre_boil_volume-((self.boil_duration/60)*BOILOFFRATE)

    @property
    def pre_boil_gravity(self):
        # print(self.hop_set.all())
        # hopset = self.hop_set.all()
        # ibu = 0
        # for hop in hopset:
        #     ibu = ibu + 5
        # return ibu
        maltset = self.malt_set.all()
        totalPPG = 0
        totalWeight = 0
        for malt in maltset:
            totalWeight = totalWeight + malt.weight
            # print('maxppg',malt.MAXPPG)
            # print('weight',malt.weight)
            maltPPG = (malt.MAXPPG*malt.weight*(self.efficiency/100))/self.pre_boil_volume
            totalPPG = totalPPG + maltPPG
        pre_boil_gravity = round(1 + totalPPG/1000,3)
        return pre_boil_gravity

    @property
    def post_boil_gravity(self):
        maltset = self.malt_set.all()
        totalPPG = 0
        totalWeight = 0
        for malt in maltset:
            totalWeight = totalWeight + malt.weight
            # print('maxppg',malt.MAXPPG)
            # print('weight',malt.weight)
            a = malt.MAXPPG*malt.weight
            b = self.efficiency/100
            c = a*b
            d = float(c)/float(self.post_boil_volume)
            maltPPG = d
            totalPPG = totalPPG + maltPPG
        post_boil_gravity = round(1 + totalPPG/1000,3)
        return post_boil_gravity
    
    @property
    def srm(self):
        maltset = self.malt_set.all()
        totalSRM = 0
        for malt in maltset:
            a = float(malt.SRM)*float(malt.weight)
            d = float(a)/float(self.post_boil_volume)
            maltSRM = d
            totalSRM = totalSRM + maltSRM
        SRM = round(totalSRM,1)
        return SRM
    
    @property
    def ibu(self):
        hopset = self.hop_set.all()
        totalIBU = 0
        for hop in hopset:
            AAU = float(hop.AA) * float(hop.weight)
            fg = 1.65*pow((0.000125),(self.post_boil_gravity-1))
            ft = (1-math.exp(-0.04*hop.time))/4.15
            a = fg*ft
            b = (AAU * a * 75)/self.post_boil_volume

            totalIBU = totalIBU + b

        IBU = round(totalIBU,1)
        return IBU
    
    @property
    def fg(self):
        a = (self.post_boil_gravity-1)*1000
        b = (a*(100-self.attenuation)/100)
        c = b/1000 + 1
        d = round(c,3)
        return d

    @property
    def abv(self):
        a = 76.08*(self.post_boil_gravity - self.fg)
        b = 1.775-self.post_boil_gravity
        c = self.fg/0.794
        abv = (float(a)/float(b)) * float(c)

        return round(abv,1)       

    @property
    def gypsumWght(self):
        return round(self.water.gypsumWght*self.post_boil_volume,2)

    @property
    def MGSO4Wght(self):
        return round(self.water.MGSO4Wght*self.post_boil_volume,2)
    
    @property
    def CaCl2Wght(self):
        return round(self.water.CaCl2Wght*self.post_boil_volume,2)

class Hop(models.Model):
    name = models.CharField(max_length=255, default = "")
    weight = models.CharField(max_length=255, default = "")
    time = models.IntegerField(default=60)
    AA = models.DecimalField(max_digits=4, decimal_places=2, default = 0.0)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name

class Malt(models.Model):
    MALT_CHOICES = [
        ('ACID', 'Acid'),
        ('AMBER', 'Amber'),
        ('AROMATIC', 'Aromatic'),
        ('SIXROW', '6-Row'),
        ('PILSNER', 'Pilsner'),
        ('TWOROW', '2-Row'),
        ('VICTORY', 'Victory'),
        ('VIENNA', 'Vienna'),
        ('MUNICH', 'Munich'),
    ]
    name = models.CharField(max_length=15, choices=MALT_CHOICES)
    weight = models.DecimalField(max_digits=4, decimal_places=2)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name

    @property
    def MAXPPG(self):
        MAXPPGS = {
            'ACID':27,
            'AMBER':35,
            'AROMATIC':36,
            'TWOROW':37,
            "SIXROW":35,
            'VICTORY':25,
            'VIENNA':35,
            'MUNICH':35,
            'PILSNER':36,
        }
        return MAXPPGS.get(self.name)

    @property
    def SRM(self):
        COLORS = {
            'ACID':3,
            'AMBER':22,
            'AROMATIC':26,
            'TWOROW':1.8,
            "SIXROW":1.8,
            'VICTORY':35,
            'VIENNA':4,
            'MUNICH':10,
            'PILSNER':3, 
        }
        return COLORS.get(self.name)

class Log(models.Model):
    batch_id = models.CharField(max_length=15, default="")
    recipe = models.ForeignKey(Recipe, on_delete=models.SET_NULL, null=True)
    og = models.DecimalField(max_digits=5, decimal_places=3, default = 1.050, blank=True)
    fg = models.DecimalField(max_digits=5, decimal_places=2, blank=True, default=1.000)
    dateBrewed = models.DateField(default=datetime.date.today)
    dateKegged = models.DateField(default=datetime.date.today)
    notes = models.CharField(max_length=300, default="")

    def __str__(self):
        return self.batch_id


class Tap(models.Model):

breweryInterface/forms.py
# import form class from django 
from django import forms 
  
# import GeeksModel from models.py 
from .models import Recipe, Log, Hop, Malt, Tap

# from django.forms import inlineformset_factory
  
# create a ModelForm 
class RecipeForm(forms.ModelForm): 
    # specify the name of model to use 
    class Meta: 
        model = Recipe
        fields = '__all__'

    # batch_id = models.CharField(max_length=15, default="")
    # recipe = models.ForeignKey(Recipe, on_delete=models.SET_NULL, null=True)
    # fg = models.CharField(max_length=5, default="")
    # date = models.DateField(default=datetime.date.today)

class LogForm(forms.ModelForm): 
    # specify the name of model to use 
    class Meta: 
        model = Log
        fields = {'batch_id', 'recipe', 'og', 'fg', 'dateBrewed', 'dateKegged'}
        # widgets = {'recipe': forms.Textarea}
        labels = {
            'batch_id': 'Batch Number',
            'og': 'Post Boil Gravity',
            'fg': 'Final Gravity',
            'dateBrewed': "Date Brewed",
            'dateKegged': 'Date Kegged'
        }

class HopForm(forms.ModelForm):
    class Meta:
        model = Hop
        fields = {'name', 'weight', 'time', 'AA', 'recipe'}

class MaltForm(forms.ModelForm):
    class Meta:
        model = Malt
        fields = {'name', 'weight', 'recipe'}

class TapForm(forms.ModelForm):
    class Meta:
        model =  Tap
        fields = '__all__'

breweryInterface/templates/breweryInterface/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" contetnt="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>BMRB Page</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/darkly/bootstrap.min.css" integrity="sha384-nNK9n28pDUDDgIiIqZ/MiyO3F4/9vsMtReZK39klb/MtkZI3/LtjSjlmyVPS3KdN" crossorigin="anonymous">
    </head>
    <body>
        <div class="container">
            <div class="col-md-12 offset-md-1 mt-5">
                <div class="jumbotron">
                    <h1 class="display-4">BMRB Interface</h1>

                    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                        <div class="collapse navbar-collapse" id="navbarNav">
                          <ul class="navbar-nav">
                            <li class="nav-item">
                              <a class="nav-link" href={% url 'recipe_list' %}>Recipes</a>
                            </li>
                            <li class="nav-item active">
                              <a class="nav-link" href={% url 'log_list' %}>Logs</a>
                            </li>
                            <li class="nav-item active">
                              <a class="nav-link" href={% url 'tap_list' %}>Taps</a>
                            </li>
                            <li class="nav-item active">
                              <a class="nav-link" href={% url 'schedule' %}>Schedule</a>
                            </li>
                          </ul>
                        </div>
                      </nav>

                    <hr class="my-4">
                    {% block content %}
                    {% endblock content %}
                </div>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>   
        
    </body>
</html>

breweryInterface/templates/breweryInterface/create_recipe.html
<form method="POST" enctype="multipart/form-data"> 
  
    <!-- Security token -->
    {% csrf_token %} 
  
    <!-- Using the formset -->
    <!-- {{ form.as_p }}  -->
    {{ formset.as_p }}
      
    <input type="submit" value="Submit"> 
</form> 

breweryInterface/templates/breweryInterface/hop_form.html
{% extends "breweryInterface/base.html" %}
{% load crispy_forms_tags %}

{% block content %}

{{ form }}

{% endblock content %}

breweryInterface/templates/breweryInterface/log_form.html
{% extends "breweryInterface/base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<form method="POST" enctype="multipart/form-data">   
    <!-- Security token -->
    {% csrf_token %}      
    
    <p class="lead">Batch Information</p>
    <div class="row">
        <div class='col-md-4'>
            {{form.batch_id|as_crispy_field}}
        </div>
        <div class='col-md-4'>
            {{form.dateBrewed|as_crispy_field}}
        </div>
    </div>
    <div class="row">
        <div class='col-md-4'>
            {{form.recipe|as_crispy_field}}
        </div>
    </div>

    <br>
    <br>

    <hr class="my-4">
    <p class="lead">Water</p>    
    <div class="row">
        <div class='col-md-4'>
            <p>Gypsum (g):</p>
        </div>
        <div class='col-md-4'>
            <p>MgSO4 (g):</p>
        </div>
        <div class='col-md-4'>
            <p>CaCl2 (g):</p>
        </div>        
    </div>
    <div class="row">
        <div class='col-md-4'>
            {{form.instance.recipe.gypsumWght}}
        </div>
        <div class='col-md-4'>
            {{form.instance.recipe.MGSO4Wght}}
        </div>
        <div class='col-md-4'>
            {{form.instance.recipe.CaCl2Wght}}
        </div>        
    </div>

    <br>
    <br>


    <hr class="my-4">
    <p class="lead">Malt</p>
    <div class="row">
        <div class='col-md-4'>
            <p>Malt</p>
        </div>
        <div class='col-md-4'>
            <p>Weight (lbs)</p>
        </div> 
        <div class='col-md-4'>
            <p>Completed?</p>
        </div> 
    </div>   
    {% for malt in form.instance.recipe.malt_set.all %}
    <div class="row">
        <div class='col-md-4'>
            <p>{{ malt.get_name_display}}</p>            
        </div>
        <div class='col-md-4'>
            <p>{{ malt.weight }}</p>
        </div> 
        <div class='col-md-4'>
            <input class="form-check-input" type="checkbox" >
        </div> 
    </div>   
    {% endfor %}
    <br>
    <br>

    <hr class="my-4">
    <p class="lead">Mash</p>
    <div class="row">
        <div class='col-md-4'>
            <p>Mash Temp</p>
        </div>
        <div class='col-md-4'>
            <p>Strike Volume</p>
        </div> 
        <div class='col-md-4'>
            <p>Strike Temp</p>
        </div> 
    </div>      
    <div class="row">
        <div class='col-md-4'>
            <p>{{form.instance.recipe.mash_temp}}</p>
        </div>
        <div class='col-md-4'>
            <p>{{form.instance.recipe.strike_volume}}</p>
        </div> 
        <div class='col-md-4'>
            <p>{{form.instance.recipe.strike_water_temp}}</p>
        </div> 
    </div>    

    <br>
    <br>
    <hr class="my-4">
    <p class="lead">Boil</p>
    <div class="row">
        <div class='col-md-4'>
            <p>Boil Duration (hours): {{form.instance.recipe.boil_duration}}</p>
        </div>
    </div>  

    <div class="row">
        <div class='col-md-4'>
            <p>Hop</p>            
        </div>
        <div class='col-md-2'>
            <p>Weight (oz)</p>
        </div> 
        <div class='col-md-2'>
            <p>Time (min)</p>
        </div> 
        <div class='col-md-4'>
            <p>Completed?</p>
        </div> 
    </div>  
    {% for hop in form.instance.recipe.hop_set.all %}
    <div class="row">
        <div class='col-md-4'>
            <p>{{ hop.name}}</p>            
        </div>
        <div class='col-md-2'>
            <p>{{ hop.weight }}</p>
        </div> 
        <div class='col-md-2'>
            <p>{{ hop.time }}</p>
        </div> 
        <div class='col-md-4'>
            <input class="form-check-input" type="checkbox" >
        </div> 
    </div>   
    {% endfor %}
    <div class="row">
        <div class='col-md-4'>
            <p>Irish Moss</p>            
        </div>
        <div class='col-md-2'>
            <p>1 tsp</p>
        </div> 
        <div class='col-md-2'>
            <p>5 min</p>
        </div> 
        <div class='col-md-4'>
            <input class="form-check-input" type="checkbox" >
        </div> 
    </div>
   
    
    <div class="row">
        <div class='col-md-4'>
            <p>{{form.og|as_crispy_field}}</p>
        </div>

    </div>  

    <br>
    <br>
    <hr class="my-4">
    <p class="lead">Ferment</p>

    <div class="row">
        <div class='col-md-4'>
            <p>Fermentation Temperature (F): {{form.instance.recipe.fermentation_temp}}</p>
        </div>
    </div>   

    <br>
    <br>
    <hr class="my-4">
    <p class="lead">Cellar</p>
    
    <div class="row">
        <div class='col-md-4'>
            {{form.fg|as_crispy_field}}
        </div>
        <div class='col-md-4'>
            {{form.dateKegged|as_crispy_field}}
        </div>
        
    </div>

    <div class="row">
        <div class='col-md-8'>
            <button type="submit" class="btn btn-success btn-block btn-lg"><i class="fas fa-database"></i>
                Submit</button>
        </div>
        <div class='col-md-4'>
            <a href="{% url 'log_list' %}" class="btn btn-secondary btn-block btn-lg">
                <i class="fas fa-stream"></i> Back to list
            </a>
        </div>
    </div>
</form> 

{% endblock content %}

breweryInterface/templates/breweryInterface/log_list.html
{% extends "breweryInterface/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="main">
    <table class="table table-borderless">
        <thead class="border-bottom font-weight-bold">
            <tr>
                <td>Batch ID</td>
                <td>Recipe</td>
                <td>Date</td>
                <td>
                    <a href="{% url 'log_insert' %}" class="btn btn-outline-success">
                        <i class="fas fa-plus"></i> Add New
                    </a>
                </td>
            </tr>
        </thead>
        <tbody>
            {% for log in logList %}
            <tr>
                <td>{{ log.batch_id }}</td>
                <td>{{ log.recipe }}</td>
                <td>{{ log.dateBrewed }}</td>
                <td>
                    <a href="{% url 'log_update' log.id %}" class="btn text-secondary px-0">
                        <i class="far fa-edit fa-lg"></i>
                    </a>
                    <form action="{% url 'log_delete' log.id %}" method="post" class="d-inline">
                        {% csrf_token %}
                        <button type="submit" class="btn">
                            <i class="far fa-trash-alt fa-lg text-danger float-right"></i>
                        </button>
                    </form>
                </td>
            </tr>
            {% endfor %} 
        </tbody>
    </table>  
</div> 

{% endblock content %}

breweryInterface/templates/breweryInterface/recipe_form.html
{% extends "breweryInterface/base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<form method="POST" enctype="multipart/form-data">   
    <!-- Security token -->
    {% csrf_token %}      

    <p class="lead">Recipe Information</p>

    <div class="row">
        <div class='col-md-4'>
            {{ form.style|as_crispy_field }}
        </div>
        <div class='col-md-4'>
            {{ form.name|as_crispy_field }}
        </div>        
    </div>

    <div class="row">
        <div class='col-md-12'>
            {{ form.description|as_crispy_field }}
        </div>
    </div>
    <div class="row">
        <div class='col-md-4'>
            {{ form.efficiency|as_crispy_field }}
        </div>
        <div class='col-md-4'>
            {{ form.attenuation|as_crispy_field }}
        </div>
        <div class='col-md-4'>
            {{ form.water|as_crispy_field }}
        </div>
    </div>

    <hr class="my-4">
    <p class="lead">Malts</p>    
    {{ maltformset.management_form}}



    {% for form in maltformset %}
    <div class="row well">
        <div class='col-md-4'>
            {{ form.name|as_crispy_field }}
        </div>
        <div class='col-md-4'>
            {{ form.weight|as_crispy_field  }}
        </div>
        <td class="hidden">{{ form.id }}</td>
    </div>        
    {% endfor %}

    <hr class="my-4">
    <p class="lead">Mash</p>    

    <div class="row">
        <div class='col-md-4'>
            {{ form.strike_volume|as_crispy_field }}
        </div>
        <div class='col-md-4'>
            {{ form.mash_temp|as_crispy_field }}
        </div>
    </div>
  
    <hr class="my-4">
    <p class="lead">Boil</p>  
    <div class="row">
        <div class='col-md-4'>
            {{ form.pre_boil_volume|as_crispy_field }}
        </div>
        <div class='col-md-4'>
            {{ form.boil_duration|as_crispy_field }}
        </div>
    </div>
      
    <hr class="my-4">
    <p class="lead">Hops</p>    
    {{ hopformset.management_form}}


    {% for form in hopformset %}
    <div class="row well">
        <div class='col-md-4'>
            {{ form.name|as_crispy_field }}
        </div>
        <div class='col-md-2'>
            {{ form.AA|as_crispy_field }}
        </div>
        <div class='col-md-2'>
            {{ form.weight|as_crispy_field  }}
        </div>
        <div class='col-md-4'>
            {{ form.time|as_crispy_field  }}
        </div>
        <td class="hidden">{{ form.id }}</td>
    </div>        
    {% endfor %}

    <hr class="my-4">
    <p class="lead">Fermentation</p>    
    <div class="row">
        <div class='col-md-4'>
            {{ form.fermentation_temp|as_crispy_field }}
        </div>
    </div>

    <div class="row">
        <div class='col-md-8'>
            <button type="submit" class="btn btn-success btn-block btn-lg"><i class="fas fa-database"></i>
                Submit</button>
        </div>
        <div class='col-md-4'>
            <a href="{% url 'recipe_list' %}" class="btn btn-secondary btn-block btn-lg">
                <i class="fas fa-stream"></i> Back to list
            </a>
        </div>
    </div>
</form> 

{% endblock content %}

breweryInterface/templates/breweryInterface/schedule.html
{% extends "breweryInterface/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
{% if graph %}
{{ graph|safe }}
{% else %}
<p>No graph was provided.</p>
{% endif %}

{% endblock content %}